#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/drivers
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/utils.js:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/utils.js
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/xdc.tci:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/xdc.tci
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/template.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/template.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/om2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/om2.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/xmlgen.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/xmlgen.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/xmlgen2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/xmlgen2.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/Warnings.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/Warnings.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/IPackage.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/IPackage.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/package.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/package.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/services/global/Clock.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/services/global/Clock.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/services/global/Trace.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/services/global/Trace.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/bld.js:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/bld.js
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/BuildEnvironment.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/PackageContents.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/PackageContents.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/_gen.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/_gen.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Library.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Library.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Executable.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Executable.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Repository.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Repository.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Configuration.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Configuration.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Script.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Script.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Manifest.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Manifest.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Utils.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/Utils.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget2.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget3.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget3.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/ITargetFilter.xs
/db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/package.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-t67/product/xdccore/Linux/xdctools_3_30_06_67_core/packages/xdc/bld/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/tirtos.bld:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/tirtos.bld
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/C28_large.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/C28_large.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/C28_float.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/C28_float.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/arm/elf/IArm.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/arm/elf/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/arm/elf/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/_utils.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/_utils.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/Linux86.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/Linux86.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/Mingw.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/Mingw.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/GCArmv6.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/GCArmv7A.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/IM.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/IM.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/M3.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/M3.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/M4.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/M4.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/M4F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/M4F.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/A8F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/A8F.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/A9F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/A9F.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/A15F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/A15F.xs
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/package.xs
package.mak: package.bld
/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/packages/ti/tirtos/build/common.bld:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/packages/ti/tirtos/build/common.bld
endif

ti.targets.arm.elf.M4.rootDir ?= /db/vendors/ti/arm/5.1.5/Linux
ti.targets.arm.elf.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/ti/targets/arm/elf/
iar.targets.arm.M4.rootDir ?= /db/vendors/iar/arm/7.20.1/Linux
iar.targets.arm.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/
gnu.targets.arm.M4.rootDir ?= /db/vendors/linaro/gcc-arm-none-eabi-4_7-2013q3
gnu.targets.arm.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm/
ti.targets.arm.elf.M3.rootDir ?= /db/vendors/ti/arm/5.1.5/Linux
iar.targets.arm.M3.rootDir ?= /db/vendors/iar/arm/7.20.1/Linux
.PRECIOUS: $(XDCCFGDIR)/%.oem4
.PHONY: all,em4 .dlls,em4 .executables,em4 test,em4
all,em4: .executables,em4
.executables,em4: .libraries,em4
.executables,em4: .dlls,em4
.dlls,em4: .libraries,em4
.libraries,em4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em4
	@$(ECHO) xdc .executables,em4
	@$(ECHO) xdc .libraries,em4
	@$(ECHO) xdc .dlls,em4

.PRECIOUS: $(XDCCFGDIR)/%.orm4
.PHONY: all,rm4 .dlls,rm4 .executables,rm4 test,rm4
all,rm4: .executables,rm4
.executables,rm4: .libraries,rm4
.executables,rm4: .dlls,rm4
.dlls,rm4: .libraries,rm4
.libraries,rm4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,rm4
	@$(ECHO) xdc .executables,rm4
	@$(ECHO) xdc .libraries,rm4
	@$(ECHO) xdc .dlls,rm4

.PRECIOUS: $(XDCCFGDIR)/%.om4g
.PHONY: all,m4g .dlls,m4g .executables,m4g test,m4g
all,m4g: .executables,m4g
.executables,m4g: .libraries,m4g
.executables,m4g: .dlls,m4g
.dlls,m4g: .libraries,m4g
.libraries,m4g: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m4g
	@$(ECHO) xdc .executables,m4g
	@$(ECHO) xdc .libraries,m4g
	@$(ECHO) xdc .dlls,m4g

.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3

.PRECIOUS: $(XDCCFGDIR)/%.orm3
.PHONY: all,rm3 .dlls,rm3 .executables,rm3 test,rm3
all,rm3: .executables,rm3
.executables,rm3: .libraries,rm3
.executables,rm3: .dlls,rm3
.dlls,rm3: .libraries,rm3
.libraries,rm3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,rm3
	@$(ECHO) xdc .executables,rm3
	@$(ECHO) xdc .libraries,rm3
	@$(ECHO) xdc .dlls,rm3

all,m3g clean,m3g .libraries,m3g .dlls,m3g .executables,m3g test,m3g:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.drivers.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.drivers" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.drivers $@

.libraries,em4 .libraries: lib/drivers_ccware_instrumented.aem4

-include lib/drivers_ccware_instrumented.aem4.mak
lib/drivers_ccware_instrumented.aem4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.oem4 package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.oem4 package/lib/lib/drivers_ccware_instrumented/I2C.oem4 package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.oem4 package/lib/lib/drivers_ccware_instrumented/PWM.oem4 package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.oem4 package/lib/lib/drivers_ccware_instrumented/SDSPI.oem4 package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.oem4 package/lib/lib/drivers_ccware_instrumented/SPI.oem4 package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.oem4 package/lib/lib/drivers_ccware_instrumented/UART.oem4 package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.oem4 package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.oem4 package/lib/lib/drivers_ccware_instrumented/Watchdog.oem4 package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.oem4  into $@ ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armar  rq $@   package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.oem4 package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.oem4 package/lib/lib/drivers_ccware_instrumented/I2C.oem4 package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.oem4 package/lib/lib/drivers_ccware_instrumented/PWM.oem4 package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.oem4 package/lib/lib/drivers_ccware_instrumented/SDSPI.oem4 package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.oem4 package/lib/lib/drivers_ccware_instrumented/SPI.oem4 package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.oem4 package/lib/lib/drivers_ccware_instrumented/UART.oem4 package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.oem4 package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.oem4 package/lib/lib/drivers_ccware_instrumented/Watchdog.oem4 package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.oem4 
lib/drivers_ccware_instrumented.aem4: export C_DIR=
lib/drivers_ccware_instrumented.aem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 clean::
	-$(RM) lib/drivers_ccware_instrumented.aem4
.libraries,em4 .libraries: lib/drivers_ccware.aem4

-include lib/drivers_ccware.aem4.mak
lib/drivers_ccware.aem4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4 package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4 package/lib/lib/drivers_ccware/I2C.oem4 package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4 package/lib/lib/drivers_ccware/PWM.oem4 package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4 package/lib/lib/drivers_ccware/SDSPI.oem4 package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4 package/lib/lib/drivers_ccware/SPI.oem4 package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4 package/lib/lib/drivers_ccware/UART.oem4 package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4 package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4 package/lib/lib/drivers_ccware/Watchdog.oem4 package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4  into $@ ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armar  rq $@   package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4 package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4 package/lib/lib/drivers_ccware/I2C.oem4 package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4 package/lib/lib/drivers_ccware/PWM.oem4 package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4 package/lib/lib/drivers_ccware/SDSPI.oem4 package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4 package/lib/lib/drivers_ccware/SPI.oem4 package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4 package/lib/lib/drivers_ccware/UART.oem4 package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4 package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4 package/lib/lib/drivers_ccware/Watchdog.oem4 package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4 
lib/drivers_ccware.aem4: export C_DIR=
lib/drivers_ccware.aem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 clean::
	-$(RM) lib/drivers_ccware.aem4
.libraries,rm4 .libraries: lib/drivers_ccware_instrumented.arm4

-include lib/drivers_ccware_instrumented.arm4.mak
lib/drivers_ccware_instrumented.arm4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.orm4 package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.orm4 package/lib/lib/drivers_ccware_instrumented/I2C.orm4 package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.orm4 package/lib/lib/drivers_ccware_instrumented/PWM.orm4 package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.orm4 package/lib/lib/drivers_ccware_instrumented/SDSPI.orm4 package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.orm4 package/lib/lib/drivers_ccware_instrumented/SPI.orm4 package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.orm4 package/lib/lib/drivers_ccware_instrumented/UART.orm4 package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.orm4 package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.orm4 package/lib/lib/drivers_ccware_instrumented/Watchdog.orm4 package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.orm4  into $@ ...
	LC_ALL=C $(iar.targets.arm.M4.rootDir)/bin/iarchive --silent -o $@   package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.orm4 package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.orm4 package/lib/lib/drivers_ccware_instrumented/I2C.orm4 package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.orm4 package/lib/lib/drivers_ccware_instrumented/PWM.orm4 package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.orm4 package/lib/lib/drivers_ccware_instrumented/SDSPI.orm4 package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.orm4 package/lib/lib/drivers_ccware_instrumented/SPI.orm4 package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.orm4 package/lib/lib/drivers_ccware_instrumented/UART.orm4 package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.orm4 package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.orm4 package/lib/lib/drivers_ccware_instrumented/Watchdog.orm4 package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.orm4 

clean,rm4 clean::
	-$(RM) lib/drivers_ccware_instrumented.arm4
.libraries,rm4 .libraries: lib/drivers_ccware.arm4

-include lib/drivers_ccware.arm4.mak
lib/drivers_ccware.arm4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_ccware/package/package_ti.drivers.orm4 package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.orm4 package/lib/lib/drivers_ccware/I2C.orm4 package/lib/lib/drivers_ccware/./i2c/I2CCC3200.orm4 package/lib/lib/drivers_ccware/PWM.orm4 package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.orm4 package/lib/lib/drivers_ccware/SDSPI.orm4 package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.orm4 package/lib/lib/drivers_ccware/SPI.orm4 package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.orm4 package/lib/lib/drivers_ccware/UART.orm4 package/lib/lib/drivers_ccware/./uart/UARTCC3200.orm4 package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.orm4 package/lib/lib/drivers_ccware/Watchdog.orm4 package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.orm4  into $@ ...
	LC_ALL=C $(iar.targets.arm.M4.rootDir)/bin/iarchive --silent -o $@   package/lib/lib/drivers_ccware/package/package_ti.drivers.orm4 package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.orm4 package/lib/lib/drivers_ccware/I2C.orm4 package/lib/lib/drivers_ccware/./i2c/I2CCC3200.orm4 package/lib/lib/drivers_ccware/PWM.orm4 package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.orm4 package/lib/lib/drivers_ccware/SDSPI.orm4 package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.orm4 package/lib/lib/drivers_ccware/SPI.orm4 package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.orm4 package/lib/lib/drivers_ccware/UART.orm4 package/lib/lib/drivers_ccware/./uart/UARTCC3200.orm4 package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.orm4 package/lib/lib/drivers_ccware/Watchdog.orm4 package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.orm4 

clean,rm4 clean::
	-$(RM) lib/drivers_ccware.arm4
.libraries,m4g .libraries: lib/drivers_ccware_instrumented.am4g

-include lib/drivers_ccware_instrumented.am4g.mak
lib/drivers_ccware_instrumented.am4g: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g package/lib/lib/drivers_ccware_instrumented/I2C.om4g package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g package/lib/lib/drivers_ccware_instrumented/PWM.om4g package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g package/lib/lib/drivers_ccware_instrumented/SPI.om4g package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g package/lib/lib/drivers_ccware_instrumented/UART.om4g package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g  into $@ ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g package/lib/lib/drivers_ccware_instrumented/I2C.om4g package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g package/lib/lib/drivers_ccware_instrumented/PWM.om4g package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g package/lib/lib/drivers_ccware_instrumented/SPI.om4g package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g package/lib/lib/drivers_ccware_instrumented/UART.om4g package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g 
lib/drivers_ccware_instrumented.am4g: export LD_LIBRARY_PATH=

clean,m4g clean::
	-$(RM) lib/drivers_ccware_instrumented.am4g
.libraries,m4g .libraries: lib/drivers_ccware.am4g

-include lib/drivers_ccware.am4g.mak
lib/drivers_ccware.am4g: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_ccware/package/package_ti.drivers.om4g package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.om4g package/lib/lib/drivers_ccware/I2C.om4g package/lib/lib/drivers_ccware/./i2c/I2CCC3200.om4g package/lib/lib/drivers_ccware/PWM.om4g package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.om4g package/lib/lib/drivers_ccware/SDSPI.om4g package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.om4g package/lib/lib/drivers_ccware/SPI.om4g package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.om4g package/lib/lib/drivers_ccware/UART.om4g package/lib/lib/drivers_ccware/./uart/UARTCC3200.om4g package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.om4g package/lib/lib/drivers_ccware/Watchdog.om4g package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.om4g  into $@ ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/drivers_ccware/package/package_ti.drivers.om4g package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.om4g package/lib/lib/drivers_ccware/I2C.om4g package/lib/lib/drivers_ccware/./i2c/I2CCC3200.om4g package/lib/lib/drivers_ccware/PWM.om4g package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.om4g package/lib/lib/drivers_ccware/SDSPI.om4g package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.om4g package/lib/lib/drivers_ccware/SPI.om4g package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.om4g package/lib/lib/drivers_ccware/UART.om4g package/lib/lib/drivers_ccware/./uart/UARTCC3200.om4g package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.om4g package/lib/lib/drivers_ccware/Watchdog.om4g package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.om4g 
lib/drivers_ccware.am4g: export LD_LIBRARY_PATH=

clean,m4g clean::
	-$(RM) lib/drivers_ccware.am4g
.libraries,em3 .libraries: lib/drivers_cc26xxware_instrumented.aem3

-include lib/drivers_cc26xxware_instrumented.aem3.mak
lib/drivers_cc26xxware_instrumented.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_cc26xxware_instrumented/package/package_ti.drivers.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./crypto/CryptoCC26XX.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./dma/UDMACC26XX.oem3 package/lib/lib/drivers_cc26xxware_instrumented/I2C.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./i2c/I2CCC26XX.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286_util.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./pin/PINCC26XX.oem3 package/lib/lib/drivers_cc26xxware_instrumented/SPI.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./spi/SPICC26XXDMA.oem3 package/lib/lib/drivers_cc26xxware_instrumented/UART.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./uart/UARTCC26XX.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armar  rq $@   package/lib/lib/drivers_cc26xxware_instrumented/package/package_ti.drivers.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./crypto/CryptoCC26XX.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./dma/UDMACC26XX.oem3 package/lib/lib/drivers_cc26xxware_instrumented/I2C.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./i2c/I2CCC26XX.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286_util.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./pin/PINCC26XX.oem3 package/lib/lib/drivers_cc26xxware_instrumented/SPI.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./spi/SPICC26XXDMA.oem3 package/lib/lib/drivers_cc26xxware_instrumented/UART.oem3 package/lib/lib/drivers_cc26xxware_instrumented/./uart/UARTCC26XX.oem3 
lib/drivers_cc26xxware_instrumented.aem3: export C_DIR=
lib/drivers_cc26xxware_instrumented.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/drivers_cc26xxware_instrumented.aem3
.libraries,em3 .libraries: lib/drivers_cc26xxware.aem3

-include lib/drivers_cc26xxware.aem3.mak
lib/drivers_cc26xxware.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3 package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3 package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3 package/lib/lib/drivers_cc26xxware/I2C.oem3 package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3 package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3 package/lib/lib/drivers_cc26xxware/SPI.oem3 package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3 package/lib/lib/drivers_cc26xxware/UART.oem3 package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armar  rq $@   package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3 package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3 package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3 package/lib/lib/drivers_cc26xxware/I2C.oem3 package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3 package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3 package/lib/lib/drivers_cc26xxware/SPI.oem3 package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3 package/lib/lib/drivers_cc26xxware/UART.oem3 package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3 
lib/drivers_cc26xxware.aem3: export C_DIR=
lib/drivers_cc26xxware.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/drivers_cc26xxware.aem3
.libraries,rm3 .libraries: lib/drivers_cc26xxware_instrumented.arm3

-include lib/drivers_cc26xxware_instrumented.arm3.mak
lib/drivers_cc26xxware_instrumented.arm3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_cc26xxware_instrumented/package/package_ti.drivers.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./crypto/CryptoCC26XX.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./dma/UDMACC26XX.orm3 package/lib/lib/drivers_cc26xxware_instrumented/I2C.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./i2c/I2CCC26XX.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286_util.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./pin/PINCC26XX.orm3 package/lib/lib/drivers_cc26xxware_instrumented/SPI.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./spi/SPICC26XXDMA.orm3 package/lib/lib/drivers_cc26xxware_instrumented/UART.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./uart/UARTCC26XX.orm3  into $@ ...
	LC_ALL=C $(iar.targets.arm.M3.rootDir)/bin/iarchive --silent -o $@   package/lib/lib/drivers_cc26xxware_instrumented/package/package_ti.drivers.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./crypto/CryptoCC26XX.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./dma/UDMACC26XX.orm3 package/lib/lib/drivers_cc26xxware_instrumented/I2C.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./i2c/I2CCC26XX.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286_util.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./pin/PINCC26XX.orm3 package/lib/lib/drivers_cc26xxware_instrumented/SPI.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./spi/SPICC26XXDMA.orm3 package/lib/lib/drivers_cc26xxware_instrumented/UART.orm3 package/lib/lib/drivers_cc26xxware_instrumented/./uart/UARTCC26XX.orm3 

clean,rm3 clean::
	-$(RM) lib/drivers_cc26xxware_instrumented.arm3
.libraries,rm3 .libraries: lib/drivers_cc26xxware.arm3

-include lib/drivers_cc26xxware.arm3.mak
lib/drivers_cc26xxware.arm3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.orm3 package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.orm3 package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.orm3 package/lib/lib/drivers_cc26xxware/I2C.orm3 package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.orm3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.orm3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.orm3 package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.orm3 package/lib/lib/drivers_cc26xxware/SPI.orm3 package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.orm3 package/lib/lib/drivers_cc26xxware/UART.orm3 package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.orm3  into $@ ...
	LC_ALL=C $(iar.targets.arm.M3.rootDir)/bin/iarchive --silent -o $@   package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.orm3 package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.orm3 package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.orm3 package/lib/lib/drivers_cc26xxware/I2C.orm3 package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.orm3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.orm3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.orm3 package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.orm3 package/lib/lib/drivers_cc26xxware/SPI.orm3 package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.orm3 package/lib/lib/drivers_cc26xxware/UART.orm3 package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.orm3 

clean,rm3 clean::
	-$(RM) lib/drivers_cc26xxware.arm3
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.drivers.oem4,copy
package_ti.drivers.oem4,copy : package_ti.drivers.oem4,0,copy package_ti.drivers.oem4,1,copy 
	@

package_ti.drivers.oem4,0,copy : package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4
package_ti.drivers.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.oem4
.PHONY: package_ti.drivers.sem4,copy
package_ti.drivers.sem4,copy : package_ti.drivers.sem4,0,copy package_ti.drivers.sem4,1,copy 
	@

package_ti.drivers.sem4,0,copy : package/lib/lib/drivers_ccware/package/package_ti.drivers.sem4
package_ti.drivers.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.sem4
.PHONY: GPIOCC3200.oem4,copy
GPIOCC3200.oem4,copy : GPIOCC3200.oem4,0,copy GPIOCC3200.oem4,1,copy 
	@

GPIOCC3200.oem4,0,copy : package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4
GPIOCC3200.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.oem4
.PHONY: GPIOCC3200.sem4,copy
GPIOCC3200.sem4,copy : GPIOCC3200.sem4,0,copy GPIOCC3200.sem4,1,copy 
	@

GPIOCC3200.sem4,0,copy : package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.sem4
GPIOCC3200.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.sem4
.PHONY: I2C.oem4,copy
I2C.oem4,copy : I2C.oem4,0,copy I2C.oem4,1,copy 
	@

I2C.oem4,0,copy : package/lib/lib/drivers_ccware/I2C.oem4
I2C.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/I2C.oem4
.PHONY: I2C.sem4,copy
I2C.sem4,copy : I2C.sem4,0,copy I2C.sem4,1,copy 
	@

I2C.sem4,0,copy : package/lib/lib/drivers_ccware/I2C.sem4
I2C.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/I2C.sem4
.PHONY: I2CCC3200.oem4,copy
I2CCC3200.oem4,copy : I2CCC3200.oem4,0,copy I2CCC3200.oem4,1,copy 
	@

I2CCC3200.oem4,0,copy : package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4
I2CCC3200.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.oem4
.PHONY: I2CCC3200.sem4,copy
I2CCC3200.sem4,copy : I2CCC3200.sem4,0,copy I2CCC3200.sem4,1,copy 
	@

I2CCC3200.sem4,0,copy : package/lib/lib/drivers_ccware/./i2c/I2CCC3200.sem4
I2CCC3200.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.sem4
.PHONY: PWM.oem4,copy
PWM.oem4,copy : PWM.oem4,0,copy PWM.oem4,1,copy 
	@

PWM.oem4,0,copy : package/lib/lib/drivers_ccware/PWM.oem4
PWM.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/PWM.oem4
.PHONY: PWM.sem4,copy
PWM.sem4,copy : PWM.sem4,0,copy PWM.sem4,1,copy 
	@

PWM.sem4,0,copy : package/lib/lib/drivers_ccware/PWM.sem4
PWM.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/PWM.sem4
.PHONY: PWMTimerCC3200.oem4,copy
PWMTimerCC3200.oem4,copy : PWMTimerCC3200.oem4,0,copy PWMTimerCC3200.oem4,1,copy 
	@

PWMTimerCC3200.oem4,0,copy : package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4
PWMTimerCC3200.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.oem4
.PHONY: PWMTimerCC3200.sem4,copy
PWMTimerCC3200.sem4,copy : PWMTimerCC3200.sem4,0,copy PWMTimerCC3200.sem4,1,copy 
	@

PWMTimerCC3200.sem4,0,copy : package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.sem4
PWMTimerCC3200.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.sem4
.PHONY: SDSPI.oem4,copy
SDSPI.oem4,copy : SDSPI.oem4,0,copy SDSPI.oem4,1,copy 
	@

SDSPI.oem4,0,copy : package/lib/lib/drivers_ccware/SDSPI.oem4
SDSPI.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/SDSPI.oem4
.PHONY: SDSPI.sem4,copy
SDSPI.sem4,copy : SDSPI.sem4,0,copy SDSPI.sem4,1,copy 
	@

SDSPI.sem4,0,copy : package/lib/lib/drivers_ccware/SDSPI.sem4
SDSPI.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/SDSPI.sem4
.PHONY: SDSPICC3200.oem4,copy
SDSPICC3200.oem4,copy : SDSPICC3200.oem4,0,copy SDSPICC3200.oem4,1,copy 
	@

SDSPICC3200.oem4,0,copy : package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4
SDSPICC3200.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.oem4
.PHONY: SDSPICC3200.sem4,copy
SDSPICC3200.sem4,copy : SDSPICC3200.sem4,0,copy SDSPICC3200.sem4,1,copy 
	@

SDSPICC3200.sem4,0,copy : package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.sem4
SDSPICC3200.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.sem4
.PHONY: SPI.oem4,copy
SPI.oem4,copy : SPI.oem4,0,copy SPI.oem4,1,copy 
	@

SPI.oem4,0,copy : package/lib/lib/drivers_ccware/SPI.oem4
SPI.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/SPI.oem4
.PHONY: SPI.sem4,copy
SPI.sem4,copy : SPI.sem4,0,copy SPI.sem4,1,copy 
	@

SPI.sem4,0,copy : package/lib/lib/drivers_ccware/SPI.sem4
SPI.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/SPI.sem4
.PHONY: SPICC3200DMA.oem4,copy
SPICC3200DMA.oem4,copy : SPICC3200DMA.oem4,0,copy SPICC3200DMA.oem4,1,copy 
	@

SPICC3200DMA.oem4,0,copy : package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4
SPICC3200DMA.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.oem4
.PHONY: SPICC3200DMA.sem4,copy
SPICC3200DMA.sem4,copy : SPICC3200DMA.sem4,0,copy SPICC3200DMA.sem4,1,copy 
	@

SPICC3200DMA.sem4,0,copy : package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.sem4
SPICC3200DMA.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.sem4
.PHONY: UART.oem4,copy
UART.oem4,copy : UART.oem4,0,copy UART.oem4,1,copy 
	@

UART.oem4,0,copy : package/lib/lib/drivers_ccware/UART.oem4
UART.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/UART.oem4
.PHONY: UART.sem4,copy
UART.sem4,copy : UART.sem4,0,copy UART.sem4,1,copy 
	@

UART.sem4,0,copy : package/lib/lib/drivers_ccware/UART.sem4
UART.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/UART.sem4
.PHONY: UARTCC3200.oem4,copy
UARTCC3200.oem4,copy : UARTCC3200.oem4,0,copy UARTCC3200.oem4,1,copy 
	@

UARTCC3200.oem4,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4
UARTCC3200.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.oem4
.PHONY: UARTCC3200.sem4,copy
UARTCC3200.sem4,copy : UARTCC3200.sem4,0,copy UARTCC3200.sem4,1,copy 
	@

UARTCC3200.sem4,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200.sem4
UARTCC3200.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.sem4
.PHONY: UARTCC3200DMA.oem4,copy
UARTCC3200DMA.oem4,copy : UARTCC3200DMA.oem4,0,copy UARTCC3200DMA.oem4,1,copy 
	@

UARTCC3200DMA.oem4,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4
UARTCC3200DMA.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.oem4
.PHONY: UARTCC3200DMA.sem4,copy
UARTCC3200DMA.sem4,copy : UARTCC3200DMA.sem4,0,copy UARTCC3200DMA.sem4,1,copy 
	@

UARTCC3200DMA.sem4,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.sem4
UARTCC3200DMA.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.sem4
.PHONY: Watchdog.oem4,copy
Watchdog.oem4,copy : Watchdog.oem4,0,copy Watchdog.oem4,1,copy 
	@

Watchdog.oem4,0,copy : package/lib/lib/drivers_ccware/Watchdog.oem4
Watchdog.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/Watchdog.oem4
.PHONY: Watchdog.sem4,copy
Watchdog.sem4,copy : Watchdog.sem4,0,copy Watchdog.sem4,1,copy 
	@

Watchdog.sem4,0,copy : package/lib/lib/drivers_ccware/Watchdog.sem4
Watchdog.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/Watchdog.sem4
.PHONY: WatchdogCC3200.oem4,copy
WatchdogCC3200.oem4,copy : WatchdogCC3200.oem4,0,copy WatchdogCC3200.oem4,1,copy 
	@

WatchdogCC3200.oem4,0,copy : package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4
WatchdogCC3200.oem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.oem4
.PHONY: WatchdogCC3200.sem4,copy
WatchdogCC3200.sem4,copy : WatchdogCC3200.sem4,0,copy WatchdogCC3200.sem4,1,copy 
	@

WatchdogCC3200.sem4,0,copy : package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.sem4
WatchdogCC3200.sem4,1,copy : package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.sem4
.PHONY: package_ti.drivers.orm4,copy
package_ti.drivers.orm4,copy : package_ti.drivers.orm4,0,copy package_ti.drivers.orm4,1,copy 
	@

package_ti.drivers.orm4,0,copy : package/lib/lib/drivers_ccware/package/package_ti.drivers.orm4
package_ti.drivers.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.orm4
.PHONY: package_ti.drivers.srm4,copy
package_ti.drivers.srm4,copy : package_ti.drivers.srm4,0,copy package_ti.drivers.srm4,1,copy 
	@

package_ti.drivers.srm4,0,copy : package/lib/lib/drivers_ccware/package/package_ti.drivers.srm4
package_ti.drivers.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.srm4
.PHONY: GPIOCC3200.orm4,copy
GPIOCC3200.orm4,copy : GPIOCC3200.orm4,0,copy GPIOCC3200.orm4,1,copy 
	@

GPIOCC3200.orm4,0,copy : package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.orm4
GPIOCC3200.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.orm4
.PHONY: GPIOCC3200.srm4,copy
GPIOCC3200.srm4,copy : GPIOCC3200.srm4,0,copy GPIOCC3200.srm4,1,copy 
	@

GPIOCC3200.srm4,0,copy : package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.srm4
GPIOCC3200.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.srm4
.PHONY: I2C.orm4,copy
I2C.orm4,copy : I2C.orm4,0,copy I2C.orm4,1,copy 
	@

I2C.orm4,0,copy : package/lib/lib/drivers_ccware/I2C.orm4
I2C.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/I2C.orm4
.PHONY: I2C.srm4,copy
I2C.srm4,copy : I2C.srm4,0,copy I2C.srm4,1,copy 
	@

I2C.srm4,0,copy : package/lib/lib/drivers_ccware/I2C.srm4
I2C.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/I2C.srm4
.PHONY: I2CCC3200.orm4,copy
I2CCC3200.orm4,copy : I2CCC3200.orm4,0,copy I2CCC3200.orm4,1,copy 
	@

I2CCC3200.orm4,0,copy : package/lib/lib/drivers_ccware/./i2c/I2CCC3200.orm4
I2CCC3200.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.orm4
.PHONY: I2CCC3200.srm4,copy
I2CCC3200.srm4,copy : I2CCC3200.srm4,0,copy I2CCC3200.srm4,1,copy 
	@

I2CCC3200.srm4,0,copy : package/lib/lib/drivers_ccware/./i2c/I2CCC3200.srm4
I2CCC3200.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.srm4
.PHONY: PWM.orm4,copy
PWM.orm4,copy : PWM.orm4,0,copy PWM.orm4,1,copy 
	@

PWM.orm4,0,copy : package/lib/lib/drivers_ccware/PWM.orm4
PWM.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/PWM.orm4
.PHONY: PWM.srm4,copy
PWM.srm4,copy : PWM.srm4,0,copy PWM.srm4,1,copy 
	@

PWM.srm4,0,copy : package/lib/lib/drivers_ccware/PWM.srm4
PWM.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/PWM.srm4
.PHONY: PWMTimerCC3200.orm4,copy
PWMTimerCC3200.orm4,copy : PWMTimerCC3200.orm4,0,copy PWMTimerCC3200.orm4,1,copy 
	@

PWMTimerCC3200.orm4,0,copy : package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.orm4
PWMTimerCC3200.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.orm4
.PHONY: PWMTimerCC3200.srm4,copy
PWMTimerCC3200.srm4,copy : PWMTimerCC3200.srm4,0,copy PWMTimerCC3200.srm4,1,copy 
	@

PWMTimerCC3200.srm4,0,copy : package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.srm4
PWMTimerCC3200.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.srm4
.PHONY: SDSPI.orm4,copy
SDSPI.orm4,copy : SDSPI.orm4,0,copy SDSPI.orm4,1,copy 
	@

SDSPI.orm4,0,copy : package/lib/lib/drivers_ccware/SDSPI.orm4
SDSPI.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/SDSPI.orm4
.PHONY: SDSPI.srm4,copy
SDSPI.srm4,copy : SDSPI.srm4,0,copy SDSPI.srm4,1,copy 
	@

SDSPI.srm4,0,copy : package/lib/lib/drivers_ccware/SDSPI.srm4
SDSPI.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/SDSPI.srm4
.PHONY: SDSPICC3200.orm4,copy
SDSPICC3200.orm4,copy : SDSPICC3200.orm4,0,copy SDSPICC3200.orm4,1,copy 
	@

SDSPICC3200.orm4,0,copy : package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.orm4
SDSPICC3200.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.orm4
.PHONY: SDSPICC3200.srm4,copy
SDSPICC3200.srm4,copy : SDSPICC3200.srm4,0,copy SDSPICC3200.srm4,1,copy 
	@

SDSPICC3200.srm4,0,copy : package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.srm4
SDSPICC3200.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.srm4
.PHONY: SPI.orm4,copy
SPI.orm4,copy : SPI.orm4,0,copy SPI.orm4,1,copy 
	@

SPI.orm4,0,copy : package/lib/lib/drivers_ccware/SPI.orm4
SPI.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/SPI.orm4
.PHONY: SPI.srm4,copy
SPI.srm4,copy : SPI.srm4,0,copy SPI.srm4,1,copy 
	@

SPI.srm4,0,copy : package/lib/lib/drivers_ccware/SPI.srm4
SPI.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/SPI.srm4
.PHONY: SPICC3200DMA.orm4,copy
SPICC3200DMA.orm4,copy : SPICC3200DMA.orm4,0,copy SPICC3200DMA.orm4,1,copy 
	@

SPICC3200DMA.orm4,0,copy : package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.orm4
SPICC3200DMA.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.orm4
.PHONY: SPICC3200DMA.srm4,copy
SPICC3200DMA.srm4,copy : SPICC3200DMA.srm4,0,copy SPICC3200DMA.srm4,1,copy 
	@

SPICC3200DMA.srm4,0,copy : package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.srm4
SPICC3200DMA.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.srm4
.PHONY: UART.orm4,copy
UART.orm4,copy : UART.orm4,0,copy UART.orm4,1,copy 
	@

UART.orm4,0,copy : package/lib/lib/drivers_ccware/UART.orm4
UART.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/UART.orm4
.PHONY: UART.srm4,copy
UART.srm4,copy : UART.srm4,0,copy UART.srm4,1,copy 
	@

UART.srm4,0,copy : package/lib/lib/drivers_ccware/UART.srm4
UART.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/UART.srm4
.PHONY: UARTCC3200.orm4,copy
UARTCC3200.orm4,copy : UARTCC3200.orm4,0,copy UARTCC3200.orm4,1,copy 
	@

UARTCC3200.orm4,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200.orm4
UARTCC3200.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.orm4
.PHONY: UARTCC3200.srm4,copy
UARTCC3200.srm4,copy : UARTCC3200.srm4,0,copy UARTCC3200.srm4,1,copy 
	@

UARTCC3200.srm4,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200.srm4
UARTCC3200.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.srm4
.PHONY: UARTCC3200DMA.orm4,copy
UARTCC3200DMA.orm4,copy : UARTCC3200DMA.orm4,0,copy UARTCC3200DMA.orm4,1,copy 
	@

UARTCC3200DMA.orm4,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.orm4
UARTCC3200DMA.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.orm4
.PHONY: UARTCC3200DMA.srm4,copy
UARTCC3200DMA.srm4,copy : UARTCC3200DMA.srm4,0,copy UARTCC3200DMA.srm4,1,copy 
	@

UARTCC3200DMA.srm4,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.srm4
UARTCC3200DMA.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.srm4
.PHONY: Watchdog.orm4,copy
Watchdog.orm4,copy : Watchdog.orm4,0,copy Watchdog.orm4,1,copy 
	@

Watchdog.orm4,0,copy : package/lib/lib/drivers_ccware/Watchdog.orm4
Watchdog.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/Watchdog.orm4
.PHONY: Watchdog.srm4,copy
Watchdog.srm4,copy : Watchdog.srm4,0,copy Watchdog.srm4,1,copy 
	@

Watchdog.srm4,0,copy : package/lib/lib/drivers_ccware/Watchdog.srm4
Watchdog.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/Watchdog.srm4
.PHONY: WatchdogCC3200.orm4,copy
WatchdogCC3200.orm4,copy : WatchdogCC3200.orm4,0,copy WatchdogCC3200.orm4,1,copy 
	@

WatchdogCC3200.orm4,0,copy : package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.orm4
WatchdogCC3200.orm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.orm4
.PHONY: WatchdogCC3200.srm4,copy
WatchdogCC3200.srm4,copy : WatchdogCC3200.srm4,0,copy WatchdogCC3200.srm4,1,copy 
	@

WatchdogCC3200.srm4,0,copy : package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.srm4
WatchdogCC3200.srm4,1,copy : package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.srm4
.PHONY: package_ti.drivers.om4g,copy
package_ti.drivers.om4g,copy : package_ti.drivers.om4g,0,copy package_ti.drivers.om4g,1,copy 
	@

package_ti.drivers.om4g,0,copy : package/lib/lib/drivers_ccware/package/package_ti.drivers.om4g
package_ti.drivers.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g
.PHONY: package_ti.drivers.sm4g,copy
package_ti.drivers.sm4g,copy : package_ti.drivers.sm4g,0,copy package_ti.drivers.sm4g,1,copy 
	@

package_ti.drivers.sm4g,0,copy : package/lib/lib/drivers_ccware/package/package_ti.drivers.sm4g
package_ti.drivers.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.sm4g
.PHONY: GPIOCC3200.om4g,copy
GPIOCC3200.om4g,copy : GPIOCC3200.om4g,0,copy GPIOCC3200.om4g,1,copy 
	@

GPIOCC3200.om4g,0,copy : package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.om4g
GPIOCC3200.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g
.PHONY: GPIOCC3200.sm4g,copy
GPIOCC3200.sm4g,copy : GPIOCC3200.sm4g,0,copy GPIOCC3200.sm4g,1,copy 
	@

GPIOCC3200.sm4g,0,copy : package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.sm4g
GPIOCC3200.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.sm4g
.PHONY: I2C.om4g,copy
I2C.om4g,copy : I2C.om4g,0,copy I2C.om4g,1,copy 
	@

I2C.om4g,0,copy : package/lib/lib/drivers_ccware/I2C.om4g
I2C.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/I2C.om4g
.PHONY: I2C.sm4g,copy
I2C.sm4g,copy : I2C.sm4g,0,copy I2C.sm4g,1,copy 
	@

I2C.sm4g,0,copy : package/lib/lib/drivers_ccware/I2C.sm4g
I2C.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/I2C.sm4g
.PHONY: I2CCC3200.om4g,copy
I2CCC3200.om4g,copy : I2CCC3200.om4g,0,copy I2CCC3200.om4g,1,copy 
	@

I2CCC3200.om4g,0,copy : package/lib/lib/drivers_ccware/./i2c/I2CCC3200.om4g
I2CCC3200.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g
.PHONY: I2CCC3200.sm4g,copy
I2CCC3200.sm4g,copy : I2CCC3200.sm4g,0,copy I2CCC3200.sm4g,1,copy 
	@

I2CCC3200.sm4g,0,copy : package/lib/lib/drivers_ccware/./i2c/I2CCC3200.sm4g
I2CCC3200.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.sm4g
.PHONY: PWM.om4g,copy
PWM.om4g,copy : PWM.om4g,0,copy PWM.om4g,1,copy 
	@

PWM.om4g,0,copy : package/lib/lib/drivers_ccware/PWM.om4g
PWM.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/PWM.om4g
.PHONY: PWM.sm4g,copy
PWM.sm4g,copy : PWM.sm4g,0,copy PWM.sm4g,1,copy 
	@

PWM.sm4g,0,copy : package/lib/lib/drivers_ccware/PWM.sm4g
PWM.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/PWM.sm4g
.PHONY: PWMTimerCC3200.om4g,copy
PWMTimerCC3200.om4g,copy : PWMTimerCC3200.om4g,0,copy PWMTimerCC3200.om4g,1,copy 
	@

PWMTimerCC3200.om4g,0,copy : package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.om4g
PWMTimerCC3200.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g
.PHONY: PWMTimerCC3200.sm4g,copy
PWMTimerCC3200.sm4g,copy : PWMTimerCC3200.sm4g,0,copy PWMTimerCC3200.sm4g,1,copy 
	@

PWMTimerCC3200.sm4g,0,copy : package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.sm4g
PWMTimerCC3200.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.sm4g
.PHONY: SDSPI.om4g,copy
SDSPI.om4g,copy : SDSPI.om4g,0,copy SDSPI.om4g,1,copy 
	@

SDSPI.om4g,0,copy : package/lib/lib/drivers_ccware/SDSPI.om4g
SDSPI.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g
.PHONY: SDSPI.sm4g,copy
SDSPI.sm4g,copy : SDSPI.sm4g,0,copy SDSPI.sm4g,1,copy 
	@

SDSPI.sm4g,0,copy : package/lib/lib/drivers_ccware/SDSPI.sm4g
SDSPI.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/SDSPI.sm4g
.PHONY: SDSPICC3200.om4g,copy
SDSPICC3200.om4g,copy : SDSPICC3200.om4g,0,copy SDSPICC3200.om4g,1,copy 
	@

SDSPICC3200.om4g,0,copy : package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.om4g
SDSPICC3200.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g
.PHONY: SDSPICC3200.sm4g,copy
SDSPICC3200.sm4g,copy : SDSPICC3200.sm4g,0,copy SDSPICC3200.sm4g,1,copy 
	@

SDSPICC3200.sm4g,0,copy : package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.sm4g
SDSPICC3200.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.sm4g
.PHONY: SPI.om4g,copy
SPI.om4g,copy : SPI.om4g,0,copy SPI.om4g,1,copy 
	@

SPI.om4g,0,copy : package/lib/lib/drivers_ccware/SPI.om4g
SPI.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/SPI.om4g
.PHONY: SPI.sm4g,copy
SPI.sm4g,copy : SPI.sm4g,0,copy SPI.sm4g,1,copy 
	@

SPI.sm4g,0,copy : package/lib/lib/drivers_ccware/SPI.sm4g
SPI.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/SPI.sm4g
.PHONY: SPICC3200DMA.om4g,copy
SPICC3200DMA.om4g,copy : SPICC3200DMA.om4g,0,copy SPICC3200DMA.om4g,1,copy 
	@

SPICC3200DMA.om4g,0,copy : package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.om4g
SPICC3200DMA.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g
.PHONY: SPICC3200DMA.sm4g,copy
SPICC3200DMA.sm4g,copy : SPICC3200DMA.sm4g,0,copy SPICC3200DMA.sm4g,1,copy 
	@

SPICC3200DMA.sm4g,0,copy : package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.sm4g
SPICC3200DMA.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.sm4g
.PHONY: UART.om4g,copy
UART.om4g,copy : UART.om4g,0,copy UART.om4g,1,copy 
	@

UART.om4g,0,copy : package/lib/lib/drivers_ccware/UART.om4g
UART.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/UART.om4g
.PHONY: UART.sm4g,copy
UART.sm4g,copy : UART.sm4g,0,copy UART.sm4g,1,copy 
	@

UART.sm4g,0,copy : package/lib/lib/drivers_ccware/UART.sm4g
UART.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/UART.sm4g
.PHONY: UARTCC3200.om4g,copy
UARTCC3200.om4g,copy : UARTCC3200.om4g,0,copy UARTCC3200.om4g,1,copy 
	@

UARTCC3200.om4g,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200.om4g
UARTCC3200.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g
.PHONY: UARTCC3200.sm4g,copy
UARTCC3200.sm4g,copy : UARTCC3200.sm4g,0,copy UARTCC3200.sm4g,1,copy 
	@

UARTCC3200.sm4g,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200.sm4g
UARTCC3200.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.sm4g
.PHONY: UARTCC3200DMA.om4g,copy
UARTCC3200DMA.om4g,copy : UARTCC3200DMA.om4g,0,copy UARTCC3200DMA.om4g,1,copy 
	@

UARTCC3200DMA.om4g,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.om4g
UARTCC3200DMA.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g
.PHONY: UARTCC3200DMA.sm4g,copy
UARTCC3200DMA.sm4g,copy : UARTCC3200DMA.sm4g,0,copy UARTCC3200DMA.sm4g,1,copy 
	@

UARTCC3200DMA.sm4g,0,copy : package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.sm4g
UARTCC3200DMA.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.sm4g
.PHONY: Watchdog.om4g,copy
Watchdog.om4g,copy : Watchdog.om4g,0,copy Watchdog.om4g,1,copy 
	@

Watchdog.om4g,0,copy : package/lib/lib/drivers_ccware/Watchdog.om4g
Watchdog.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g
.PHONY: Watchdog.sm4g,copy
Watchdog.sm4g,copy : Watchdog.sm4g,0,copy Watchdog.sm4g,1,copy 
	@

Watchdog.sm4g,0,copy : package/lib/lib/drivers_ccware/Watchdog.sm4g
Watchdog.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/Watchdog.sm4g
.PHONY: WatchdogCC3200.om4g,copy
WatchdogCC3200.om4g,copy : WatchdogCC3200.om4g,0,copy WatchdogCC3200.om4g,1,copy 
	@

WatchdogCC3200.om4g,0,copy : package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.om4g
WatchdogCC3200.om4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g
.PHONY: WatchdogCC3200.sm4g,copy
WatchdogCC3200.sm4g,copy : WatchdogCC3200.sm4g,0,copy WatchdogCC3200.sm4g,1,copy 
	@

WatchdogCC3200.sm4g,0,copy : package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.sm4g
WatchdogCC3200.sm4g,1,copy : package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.sm4g
.PHONY: package_ti.drivers.oem3,copy
package_ti.drivers.oem3,copy : package_ti.drivers.oem3,0,copy package_ti.drivers.oem3,1,copy 
	@

package_ti.drivers.oem3,0,copy : package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3
package_ti.drivers.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/package/package_ti.drivers.oem3
.PHONY: package_ti.drivers.sem3,copy
package_ti.drivers.sem3,copy : package_ti.drivers.sem3,0,copy package_ti.drivers.sem3,1,copy 
	@

package_ti.drivers.sem3,0,copy : package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.sem3
package_ti.drivers.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/package/package_ti.drivers.sem3
.PHONY: CryptoCC26XX.oem3,copy
CryptoCC26XX.oem3,copy : CryptoCC26XX.oem3,0,copy CryptoCC26XX.oem3,1,copy 
	@

CryptoCC26XX.oem3,0,copy : package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3
CryptoCC26XX.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./crypto/CryptoCC26XX.oem3
.PHONY: CryptoCC26XX.sem3,copy
CryptoCC26XX.sem3,copy : CryptoCC26XX.sem3,0,copy CryptoCC26XX.sem3,1,copy 
	@

CryptoCC26XX.sem3,0,copy : package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.sem3
CryptoCC26XX.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./crypto/CryptoCC26XX.sem3
.PHONY: UDMACC26XX.oem3,copy
UDMACC26XX.oem3,copy : UDMACC26XX.oem3,0,copy UDMACC26XX.oem3,1,copy 
	@

UDMACC26XX.oem3,0,copy : package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3
UDMACC26XX.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./dma/UDMACC26XX.oem3
.PHONY: UDMACC26XX.sem3,copy
UDMACC26XX.sem3,copy : UDMACC26XX.sem3,0,copy UDMACC26XX.sem3,1,copy 
	@

UDMACC26XX.sem3,0,copy : package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.sem3
UDMACC26XX.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./dma/UDMACC26XX.sem3
.PHONY: I2C.oem3,copy
I2C.oem3,copy : I2C.oem3,0,copy I2C.oem3,1,copy 
	@

I2C.oem3,0,copy : package/lib/lib/drivers_cc26xxware/I2C.oem3
I2C.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/I2C.oem3
.PHONY: I2C.sem3,copy
I2C.sem3,copy : I2C.sem3,0,copy I2C.sem3,1,copy 
	@

I2C.sem3,0,copy : package/lib/lib/drivers_cc26xxware/I2C.sem3
I2C.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/I2C.sem3
.PHONY: I2CCC26XX.oem3,copy
I2CCC26XX.oem3,copy : I2CCC26XX.oem3,0,copy I2CCC26XX.oem3,1,copy 
	@

I2CCC26XX.oem3,0,copy : package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3
I2CCC26XX.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./i2c/I2CCC26XX.oem3
.PHONY: I2CCC26XX.sem3,copy
I2CCC26XX.sem3,copy : I2CCC26XX.sem3,0,copy I2CCC26XX.sem3,1,copy 
	@

I2CCC26XX.sem3,0,copy : package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.sem3
I2CCC26XX.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./i2c/I2CCC26XX.sem3
.PHONY: LCDDogm1286.oem3,copy
LCDDogm1286.oem3,copy : LCDDogm1286.oem3,0,copy LCDDogm1286.oem3,1,copy 
	@

LCDDogm1286.oem3,0,copy : package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3
LCDDogm1286.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286.oem3
.PHONY: LCDDogm1286.sem3,copy
LCDDogm1286.sem3,copy : LCDDogm1286.sem3,0,copy LCDDogm1286.sem3,1,copy 
	@

LCDDogm1286.sem3,0,copy : package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.sem3
LCDDogm1286.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286.sem3
.PHONY: LCDDogm1286_util.oem3,copy
LCDDogm1286_util.oem3,copy : LCDDogm1286_util.oem3,0,copy LCDDogm1286_util.oem3,1,copy 
	@

LCDDogm1286_util.oem3,0,copy : package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3
LCDDogm1286_util.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286_util.oem3
.PHONY: LCDDogm1286_util.sem3,copy
LCDDogm1286_util.sem3,copy : LCDDogm1286_util.sem3,0,copy LCDDogm1286_util.sem3,1,copy 
	@

LCDDogm1286_util.sem3,0,copy : package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.sem3
LCDDogm1286_util.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286_util.sem3
.PHONY: PINCC26XX.oem3,copy
PINCC26XX.oem3,copy : PINCC26XX.oem3,0,copy PINCC26XX.oem3,1,copy 
	@

PINCC26XX.oem3,0,copy : package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3
PINCC26XX.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./pin/PINCC26XX.oem3
.PHONY: PINCC26XX.sem3,copy
PINCC26XX.sem3,copy : PINCC26XX.sem3,0,copy PINCC26XX.sem3,1,copy 
	@

PINCC26XX.sem3,0,copy : package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.sem3
PINCC26XX.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./pin/PINCC26XX.sem3
.PHONY: SPI.oem3,copy
SPI.oem3,copy : SPI.oem3,0,copy SPI.oem3,1,copy 
	@

SPI.oem3,0,copy : package/lib/lib/drivers_cc26xxware/SPI.oem3
SPI.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/SPI.oem3
.PHONY: SPI.sem3,copy
SPI.sem3,copy : SPI.sem3,0,copy SPI.sem3,1,copy 
	@

SPI.sem3,0,copy : package/lib/lib/drivers_cc26xxware/SPI.sem3
SPI.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/SPI.sem3
.PHONY: SPICC26XXDMA.oem3,copy
SPICC26XXDMA.oem3,copy : SPICC26XXDMA.oem3,0,copy SPICC26XXDMA.oem3,1,copy 
	@

SPICC26XXDMA.oem3,0,copy : package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3
SPICC26XXDMA.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./spi/SPICC26XXDMA.oem3
.PHONY: SPICC26XXDMA.sem3,copy
SPICC26XXDMA.sem3,copy : SPICC26XXDMA.sem3,0,copy SPICC26XXDMA.sem3,1,copy 
	@

SPICC26XXDMA.sem3,0,copy : package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.sem3
SPICC26XXDMA.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./spi/SPICC26XXDMA.sem3
.PHONY: UART.oem3,copy
UART.oem3,copy : UART.oem3,0,copy UART.oem3,1,copy 
	@

UART.oem3,0,copy : package/lib/lib/drivers_cc26xxware/UART.oem3
UART.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/UART.oem3
.PHONY: UART.sem3,copy
UART.sem3,copy : UART.sem3,0,copy UART.sem3,1,copy 
	@

UART.sem3,0,copy : package/lib/lib/drivers_cc26xxware/UART.sem3
UART.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/UART.sem3
.PHONY: UARTCC26XX.oem3,copy
UARTCC26XX.oem3,copy : UARTCC26XX.oem3,0,copy UARTCC26XX.oem3,1,copy 
	@

UARTCC26XX.oem3,0,copy : package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3
UARTCC26XX.oem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./uart/UARTCC26XX.oem3
.PHONY: UARTCC26XX.sem3,copy
UARTCC26XX.sem3,copy : UARTCC26XX.sem3,0,copy UARTCC26XX.sem3,1,copy 
	@

UARTCC26XX.sem3,0,copy : package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.sem3
UARTCC26XX.sem3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./uart/UARTCC26XX.sem3
.PHONY: package_ti.drivers.orm3,copy
package_ti.drivers.orm3,copy : package_ti.drivers.orm3,0,copy package_ti.drivers.orm3,1,copy 
	@

package_ti.drivers.orm3,0,copy : package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.orm3
package_ti.drivers.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/package/package_ti.drivers.orm3
.PHONY: package_ti.drivers.srm3,copy
package_ti.drivers.srm3,copy : package_ti.drivers.srm3,0,copy package_ti.drivers.srm3,1,copy 
	@

package_ti.drivers.srm3,0,copy : package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.srm3
package_ti.drivers.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/package/package_ti.drivers.srm3
.PHONY: CryptoCC26XX.orm3,copy
CryptoCC26XX.orm3,copy : CryptoCC26XX.orm3,0,copy CryptoCC26XX.orm3,1,copy 
	@

CryptoCC26XX.orm3,0,copy : package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.orm3
CryptoCC26XX.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./crypto/CryptoCC26XX.orm3
.PHONY: CryptoCC26XX.srm3,copy
CryptoCC26XX.srm3,copy : CryptoCC26XX.srm3,0,copy CryptoCC26XX.srm3,1,copy 
	@

CryptoCC26XX.srm3,0,copy : package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.srm3
CryptoCC26XX.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./crypto/CryptoCC26XX.srm3
.PHONY: UDMACC26XX.orm3,copy
UDMACC26XX.orm3,copy : UDMACC26XX.orm3,0,copy UDMACC26XX.orm3,1,copy 
	@

UDMACC26XX.orm3,0,copy : package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.orm3
UDMACC26XX.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./dma/UDMACC26XX.orm3
.PHONY: UDMACC26XX.srm3,copy
UDMACC26XX.srm3,copy : UDMACC26XX.srm3,0,copy UDMACC26XX.srm3,1,copy 
	@

UDMACC26XX.srm3,0,copy : package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.srm3
UDMACC26XX.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./dma/UDMACC26XX.srm3
.PHONY: I2C.orm3,copy
I2C.orm3,copy : I2C.orm3,0,copy I2C.orm3,1,copy 
	@

I2C.orm3,0,copy : package/lib/lib/drivers_cc26xxware/I2C.orm3
I2C.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/I2C.orm3
.PHONY: I2C.srm3,copy
I2C.srm3,copy : I2C.srm3,0,copy I2C.srm3,1,copy 
	@

I2C.srm3,0,copy : package/lib/lib/drivers_cc26xxware/I2C.srm3
I2C.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/I2C.srm3
.PHONY: I2CCC26XX.orm3,copy
I2CCC26XX.orm3,copy : I2CCC26XX.orm3,0,copy I2CCC26XX.orm3,1,copy 
	@

I2CCC26XX.orm3,0,copy : package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.orm3
I2CCC26XX.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./i2c/I2CCC26XX.orm3
.PHONY: I2CCC26XX.srm3,copy
I2CCC26XX.srm3,copy : I2CCC26XX.srm3,0,copy I2CCC26XX.srm3,1,copy 
	@

I2CCC26XX.srm3,0,copy : package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.srm3
I2CCC26XX.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./i2c/I2CCC26XX.srm3
.PHONY: LCDDogm1286.orm3,copy
LCDDogm1286.orm3,copy : LCDDogm1286.orm3,0,copy LCDDogm1286.orm3,1,copy 
	@

LCDDogm1286.orm3,0,copy : package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.orm3
LCDDogm1286.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286.orm3
.PHONY: LCDDogm1286.srm3,copy
LCDDogm1286.srm3,copy : LCDDogm1286.srm3,0,copy LCDDogm1286.srm3,1,copy 
	@

LCDDogm1286.srm3,0,copy : package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.srm3
LCDDogm1286.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286.srm3
.PHONY: LCDDogm1286_util.orm3,copy
LCDDogm1286_util.orm3,copy : LCDDogm1286_util.orm3,0,copy LCDDogm1286_util.orm3,1,copy 
	@

LCDDogm1286_util.orm3,0,copy : package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.orm3
LCDDogm1286_util.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286_util.orm3
.PHONY: LCDDogm1286_util.srm3,copy
LCDDogm1286_util.srm3,copy : LCDDogm1286_util.srm3,0,copy LCDDogm1286_util.srm3,1,copy 
	@

LCDDogm1286_util.srm3,0,copy : package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.srm3
LCDDogm1286_util.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./lcd/LCDDogm1286_util.srm3
.PHONY: PINCC26XX.orm3,copy
PINCC26XX.orm3,copy : PINCC26XX.orm3,0,copy PINCC26XX.orm3,1,copy 
	@

PINCC26XX.orm3,0,copy : package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.orm3
PINCC26XX.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./pin/PINCC26XX.orm3
.PHONY: PINCC26XX.srm3,copy
PINCC26XX.srm3,copy : PINCC26XX.srm3,0,copy PINCC26XX.srm3,1,copy 
	@

PINCC26XX.srm3,0,copy : package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.srm3
PINCC26XX.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./pin/PINCC26XX.srm3
.PHONY: SPI.orm3,copy
SPI.orm3,copy : SPI.orm3,0,copy SPI.orm3,1,copy 
	@

SPI.orm3,0,copy : package/lib/lib/drivers_cc26xxware/SPI.orm3
SPI.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/SPI.orm3
.PHONY: SPI.srm3,copy
SPI.srm3,copy : SPI.srm3,0,copy SPI.srm3,1,copy 
	@

SPI.srm3,0,copy : package/lib/lib/drivers_cc26xxware/SPI.srm3
SPI.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/SPI.srm3
.PHONY: SPICC26XXDMA.orm3,copy
SPICC26XXDMA.orm3,copy : SPICC26XXDMA.orm3,0,copy SPICC26XXDMA.orm3,1,copy 
	@

SPICC26XXDMA.orm3,0,copy : package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.orm3
SPICC26XXDMA.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./spi/SPICC26XXDMA.orm3
.PHONY: SPICC26XXDMA.srm3,copy
SPICC26XXDMA.srm3,copy : SPICC26XXDMA.srm3,0,copy SPICC26XXDMA.srm3,1,copy 
	@

SPICC26XXDMA.srm3,0,copy : package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.srm3
SPICC26XXDMA.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./spi/SPICC26XXDMA.srm3
.PHONY: UART.orm3,copy
UART.orm3,copy : UART.orm3,0,copy UART.orm3,1,copy 
	@

UART.orm3,0,copy : package/lib/lib/drivers_cc26xxware/UART.orm3
UART.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/UART.orm3
.PHONY: UART.srm3,copy
UART.srm3,copy : UART.srm3,0,copy UART.srm3,1,copy 
	@

UART.srm3,0,copy : package/lib/lib/drivers_cc26xxware/UART.srm3
UART.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/UART.srm3
.PHONY: UARTCC26XX.orm3,copy
UARTCC26XX.orm3,copy : UARTCC26XX.orm3,0,copy UARTCC26XX.orm3,1,copy 
	@

UARTCC26XX.orm3,0,copy : package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.orm3
UARTCC26XX.orm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./uart/UARTCC26XX.orm3
.PHONY: UARTCC26XX.srm3,copy
UARTCC26XX.srm3,copy : UARTCC26XX.srm3,0,copy UARTCC26XX.srm3,1,copy 
	@

UARTCC26XX.srm3,0,copy : package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.srm3
UARTCC26XX.srm3,1,copy : package/lib/lib/drivers_cc26xxware_instrumented/./uart/UARTCC26XX.srm3

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_drivers
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_drivers.tar.dep
endif
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: package/package.bld.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: package/build.cfg
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: package.bld
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: rovdriver.xs
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./crypto/CryptoCC26XX.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./dma/UDMACC26XX.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: EMAC.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./emac/EMACTiva.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./emac/EMACSnow.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: EMAC.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: GPIO.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: GPIO.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: I2C.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./i2c/I2CTiva.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./i2c/I2CCC3200.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./i2c/I2CCC26XX.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./i2c/I2CUSCIB.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./i2c/I2CEUSCIB.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: I2C.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./lcd/LCDDogm1286.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./lcd/LCDDogm1286_util.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: PIN.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./pin/PINCC26XX.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: PWM.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./pwm/PWMTimerCC3200.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./pwm/PWMTimerTiva.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./pwm/PWMTiva.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: PWM.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: SDSPI.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPICC3200.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPITiva.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPIUSCIA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPIUSCIB.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPIEUSCIA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPIEUSCIB.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: SDSPI.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: SPI.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPITivaDMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPICC3200DMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPICC26XXDMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPIUSCIADMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPIUSCIBDMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPIEUSCIADMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPIEUSCIBDMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: SPI.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: UART.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTTiva.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTTivaDMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTCC3200.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTCC26XX.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTCC3200DMA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTUSCIA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTEUSCIA.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: UART.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: USBMSCHFatFs.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./usbmschfatfs/USBMSCHFatFsTiva.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: USBMSCHFatFs.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: Watchdog.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./watchdog/WatchdogTiva.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./watchdog/WatchdogCC3200.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./watchdog/WatchdogMSP430.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: Watchdog.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: WiFi.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./wifi/WiFiTivaCC3000.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./wifi/WiFiMSP430CC3000.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./wifi/cc3000
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./wifi/WiFiCC3100.h
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./wifi/cc3100/Simplelink
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: WiFi.xml
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./i2c/I2CUSCIB.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPIUSCIADMA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPIUSCIBDMA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPIEUSCIADMA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPIEUSCIBDMA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPIUSCIA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPIUSCIB.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTUSCIA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./wifi/WiFiMSP430CC3000.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_ccware_instrumented.aem4
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: package/package_ti.drivers.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./gpio/GPIOCC3200.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: I2C.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./i2c/I2CCC3200.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: PWM.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./pwm/PWMTimerCC3200.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: SDSPI.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./sdspi/SDSPICC3200.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: SPI.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPICC3200DMA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: UART.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTCC3200.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTCC3200DMA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: Watchdog.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./watchdog/WatchdogCC3200.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_ccware.aem4
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_ccware_instrumented.arm4
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_ccware.arm4
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_ccware_instrumented.am4g
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_ccware.am4g
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_cc26xxware_instrumented.aem3
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./crypto/CryptoCC26XX.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./dma/UDMACC26XX.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./i2c/I2CCC26XX.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./lcd/LCDDogm1286.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./lcd/LCDDogm1286_util.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./pin/PINCC26XX.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./spi/SPICC26XXDMA.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: ./uart/UARTCC26XX.c
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_cc26xxware.aem3
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_cc26xxware_instrumented.arm3
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: lib/drivers_cc26xxware.arm3
package/rel/ti_drivers/ti/drivers/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_drivers.tar: package/rel/ti_drivers.xdc.inc package/rel/ti_drivers/ti/drivers/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_drivers.xdc.inc,package/rel/ti_drivers.tar.dep)


release release,ti_drivers: all ti_drivers.tar
clean:: .clean
	-$(RM) ti_drivers.tar
	-$(RM) package/rel/ti_drivers.xdc.inc
	-$(RM) package/rel/ti_drivers.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented/package))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented/package)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented/gpio))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented/gpio)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented/i2c))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented/i2c)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented/pwm))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented/pwm)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented/sdspi))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented/sdspi)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented/spi))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented/spi)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented/uart))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented/uart)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware_instrumented/watchdog))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware_instrumented/watchdog)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware/package))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware/package)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware/gpio))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware/gpio)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware/i2c))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware/i2c)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware/pwm))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware/pwm)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware/sdspi))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware/sdspi)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware/spi))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware/spi)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware/uart))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware/uart)
endif
ifeq (,$(wildcard package/lib/lib/drivers_ccware/watchdog))
    $(shell $(MKDIR) package/lib/lib/drivers_ccware/watchdog)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented/package))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented/package)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented/crypto))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented/crypto)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented/dma))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented/dma)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented/i2c))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented/i2c)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented/lcd))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented/lcd)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented/pin))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented/pin)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented/spi))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented/spi)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware_instrumented/uart))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware_instrumented/uart)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware/package))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware/package)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware/crypto))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware/crypto)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware/dma))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware/dma)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware/i2c))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware/i2c)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware/lcd))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware/lcd)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware/pin))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware/pin)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware/spi))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware/spi)
endif
ifeq (,$(wildcard package/lib/lib/drivers_cc26xxware/uart))
    $(shell $(MKDIR) package/lib/lib/drivers_cc26xxware/uart)
endif
endif
clean::
	-$(RMDIR) package


