#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4{1,0,5.1,5
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4.dep
package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4: | .interfaces
package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4: package/package_ti.drivers.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/package -fr=./package/lib/lib/drivers_ccware/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/package -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/package -fr=./package/lib/lib/drivers_ccware/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4: export C_DIR=
package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/package/package_ti.drivers.sem4: | .interfaces
package/lib/lib/drivers_ccware/package/package_ti.drivers.sem4: package/package_ti.drivers.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/package -fr=./package/lib/lib/drivers_ccware/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/package -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/package -fr=./package/lib/lib/drivers_ccware/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/package/package_ti.drivers.sem4: export C_DIR=
package/lib/lib/drivers_ccware/package/package_ti.drivers.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4.dep
package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4: | .interfaces
package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4: ./gpio/GPIOCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./gpio -fr=./package/lib/lib/drivers_ccware/./gpio -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./gpio -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./gpio -fr=./package/lib/lib/drivers_ccware/./gpio
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4: export C_DIR=
package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.sem4: | .interfaces
package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.sem4: ./gpio/GPIOCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./gpio -fr=./package/lib/lib/drivers_ccware/./gpio -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./gpio -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./gpio -fr=./package/lib/lib/drivers_ccware/./gpio
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.sem4: export C_DIR=
package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/I2C.oem4.dep
package/lib/lib/drivers_ccware/I2C.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/I2C.oem4: | .interfaces
package/lib/lib/drivers_ccware/I2C.oem4: I2C.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/I2C.oem4: export C_DIR=
package/lib/lib/drivers_ccware/I2C.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/I2C.sem4: | .interfaces
package/lib/lib/drivers_ccware/I2C.sem4: I2C.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/I2C.sem4: export C_DIR=
package/lib/lib/drivers_ccware/I2C.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4.dep
package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4: | .interfaces
package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4: ./i2c/I2CCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./i2c -fr=./package/lib/lib/drivers_ccware/./i2c -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./i2c -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./i2c -fr=./package/lib/lib/drivers_ccware/./i2c
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4: export C_DIR=
package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/./i2c/I2CCC3200.sem4: | .interfaces
package/lib/lib/drivers_ccware/./i2c/I2CCC3200.sem4: ./i2c/I2CCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./i2c -fr=./package/lib/lib/drivers_ccware/./i2c -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./i2c -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./i2c -fr=./package/lib/lib/drivers_ccware/./i2c
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./i2c/I2CCC3200.sem4: export C_DIR=
package/lib/lib/drivers_ccware/./i2c/I2CCC3200.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/PWM.oem4.dep
package/lib/lib/drivers_ccware/PWM.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/PWM.oem4: | .interfaces
package/lib/lib/drivers_ccware/PWM.oem4: PWM.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/PWM.oem4: export C_DIR=
package/lib/lib/drivers_ccware/PWM.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/PWM.sem4: | .interfaces
package/lib/lib/drivers_ccware/PWM.sem4: PWM.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/PWM.sem4: export C_DIR=
package/lib/lib/drivers_ccware/PWM.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4.dep
package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4: | .interfaces
package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4: ./pwm/PWMTimerCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./pwm -fr=./package/lib/lib/drivers_ccware/./pwm -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./pwm -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./pwm -fr=./package/lib/lib/drivers_ccware/./pwm
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4: export C_DIR=
package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.sem4: | .interfaces
package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.sem4: ./pwm/PWMTimerCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./pwm -fr=./package/lib/lib/drivers_ccware/./pwm -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./pwm -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./pwm -fr=./package/lib/lib/drivers_ccware/./pwm
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.sem4: export C_DIR=
package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/SDSPI.oem4.dep
package/lib/lib/drivers_ccware/SDSPI.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/SDSPI.oem4: | .interfaces
package/lib/lib/drivers_ccware/SDSPI.oem4: SDSPI.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/SDSPI.oem4: export C_DIR=
package/lib/lib/drivers_ccware/SDSPI.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/SDSPI.sem4: | .interfaces
package/lib/lib/drivers_ccware/SDSPI.sem4: SDSPI.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/SDSPI.sem4: export C_DIR=
package/lib/lib/drivers_ccware/SDSPI.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4.dep
package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4: | .interfaces
package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4: ./sdspi/SDSPICC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./sdspi -fr=./package/lib/lib/drivers_ccware/./sdspi -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./sdspi -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./sdspi -fr=./package/lib/lib/drivers_ccware/./sdspi
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4: export C_DIR=
package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.sem4: | .interfaces
package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.sem4: ./sdspi/SDSPICC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./sdspi -fr=./package/lib/lib/drivers_ccware/./sdspi -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./sdspi -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./sdspi -fr=./package/lib/lib/drivers_ccware/./sdspi
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.sem4: export C_DIR=
package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/SPI.oem4.dep
package/lib/lib/drivers_ccware/SPI.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/SPI.oem4: | .interfaces
package/lib/lib/drivers_ccware/SPI.oem4: SPI.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/SPI.oem4: export C_DIR=
package/lib/lib/drivers_ccware/SPI.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/SPI.sem4: | .interfaces
package/lib/lib/drivers_ccware/SPI.sem4: SPI.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/SPI.sem4: export C_DIR=
package/lib/lib/drivers_ccware/SPI.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4.dep
package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4: | .interfaces
package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4: ./spi/SPICC3200DMA.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./spi -fr=./package/lib/lib/drivers_ccware/./spi -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./spi -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./spi -fr=./package/lib/lib/drivers_ccware/./spi
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4: export C_DIR=
package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.sem4: | .interfaces
package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.sem4: ./spi/SPICC3200DMA.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./spi -fr=./package/lib/lib/drivers_ccware/./spi -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./spi -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./spi -fr=./package/lib/lib/drivers_ccware/./spi
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.sem4: export C_DIR=
package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/UART.oem4.dep
package/lib/lib/drivers_ccware/UART.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/UART.oem4: | .interfaces
package/lib/lib/drivers_ccware/UART.oem4: UART.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/UART.oem4: export C_DIR=
package/lib/lib/drivers_ccware/UART.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/UART.sem4: | .interfaces
package/lib/lib/drivers_ccware/UART.sem4: UART.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/UART.sem4: export C_DIR=
package/lib/lib/drivers_ccware/UART.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4.dep
package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4: | .interfaces
package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4: ./uart/UARTCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./uart -fr=./package/lib/lib/drivers_ccware/./uart -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./uart -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./uart -fr=./package/lib/lib/drivers_ccware/./uart
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4: export C_DIR=
package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/./uart/UARTCC3200.sem4: | .interfaces
package/lib/lib/drivers_ccware/./uart/UARTCC3200.sem4: ./uart/UARTCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./uart -fr=./package/lib/lib/drivers_ccware/./uart -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./uart -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./uart -fr=./package/lib/lib/drivers_ccware/./uart
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./uart/UARTCC3200.sem4: export C_DIR=
package/lib/lib/drivers_ccware/./uart/UARTCC3200.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4.dep
package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4: | .interfaces
package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4: ./uart/UARTCC3200DMA.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./uart -fr=./package/lib/lib/drivers_ccware/./uart -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./uart -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./uart -fr=./package/lib/lib/drivers_ccware/./uart
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4: export C_DIR=
package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.sem4: | .interfaces
package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.sem4: ./uart/UARTCC3200DMA.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./uart -fr=./package/lib/lib/drivers_ccware/./uart -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./uart -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./uart -fr=./package/lib/lib/drivers_ccware/./uart
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.sem4: export C_DIR=
package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/Watchdog.oem4.dep
package/lib/lib/drivers_ccware/Watchdog.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/Watchdog.oem4: | .interfaces
package/lib/lib/drivers_ccware/Watchdog.oem4: Watchdog.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/Watchdog.oem4: export C_DIR=
package/lib/lib/drivers_ccware/Watchdog.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/Watchdog.sem4: | .interfaces
package/lib/lib/drivers_ccware/Watchdog.sem4: Watchdog.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware -fr=./package/lib/lib/drivers_ccware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/Watchdog.sem4: export C_DIR=
package/lib/lib/drivers_ccware/Watchdog.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4.dep
package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4.dep: ;
endif

package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4: | .interfaces
package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4: ./watchdog/WatchdogCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./watchdog -fr=./package/lib/lib/drivers_ccware/./watchdog -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./watchdog -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./watchdog -fr=./package/lib/lib/drivers_ccware/./watchdog
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4: export C_DIR=
package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.sem4: | .interfaces
package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.sem4: ./watchdog/WatchdogCC3200.c lib/drivers_ccware.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./watchdog -fr=./package/lib/lib/drivers_ccware/./watchdog -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_ccware/./watchdog -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs   -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_1_5 -O2  -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/drivers_ccware/./watchdog -fr=./package/lib/lib/drivers_ccware/./watchdog
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.sem4: export C_DIR=
package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 ::
	-$(RM) package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4
	-$(RM) package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4
	-$(RM) package/lib/lib/drivers_ccware/I2C.oem4
	-$(RM) package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4
	-$(RM) package/lib/lib/drivers_ccware/PWM.oem4
	-$(RM) package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4
	-$(RM) package/lib/lib/drivers_ccware/SDSPI.oem4
	-$(RM) package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4
	-$(RM) package/lib/lib/drivers_ccware/SPI.oem4
	-$(RM) package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4
	-$(RM) package/lib/lib/drivers_ccware/UART.oem4
	-$(RM) package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4
	-$(RM) package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4
	-$(RM) package/lib/lib/drivers_ccware/Watchdog.oem4
	-$(RM) package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4
	-$(RM) package/lib/lib/drivers_ccware/package/package_ti.drivers.sem4
	-$(RM) package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.sem4
	-$(RM) package/lib/lib/drivers_ccware/I2C.sem4
	-$(RM) package/lib/lib/drivers_ccware/./i2c/I2CCC3200.sem4
	-$(RM) package/lib/lib/drivers_ccware/PWM.sem4
	-$(RM) package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.sem4
	-$(RM) package/lib/lib/drivers_ccware/SDSPI.sem4
	-$(RM) package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.sem4
	-$(RM) package/lib/lib/drivers_ccware/SPI.sem4
	-$(RM) package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.sem4
	-$(RM) package/lib/lib/drivers_ccware/UART.sem4
	-$(RM) package/lib/lib/drivers_ccware/./uart/UARTCC3200.sem4
	-$(RM) package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.sem4
	-$(RM) package/lib/lib/drivers_ccware/Watchdog.sem4
	-$(RM) package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.sem4

lib/drivers_ccware.aem4: package/lib/lib/drivers_ccware/package/package_ti.drivers.oem4 package/lib/lib/drivers_ccware/./gpio/GPIOCC3200.oem4 package/lib/lib/drivers_ccware/I2C.oem4 package/lib/lib/drivers_ccware/./i2c/I2CCC3200.oem4 package/lib/lib/drivers_ccware/PWM.oem4 package/lib/lib/drivers_ccware/./pwm/PWMTimerCC3200.oem4 package/lib/lib/drivers_ccware/SDSPI.oem4 package/lib/lib/drivers_ccware/./sdspi/SDSPICC3200.oem4 package/lib/lib/drivers_ccware/SPI.oem4 package/lib/lib/drivers_ccware/./spi/SPICC3200DMA.oem4 package/lib/lib/drivers_ccware/UART.oem4 package/lib/lib/drivers_ccware/./uart/UARTCC3200.oem4 package/lib/lib/drivers_ccware/./uart/UARTCC3200DMA.oem4 package/lib/lib/drivers_ccware/Watchdog.oem4 package/lib/lib/drivers_ccware/./watchdog/WatchdogCC3200.oem4 lib/drivers_ccware.aem4.mak

clean::
	-$(RM) lib/drivers_ccware.aem4.mak
