#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M4{1,0,4.7,4
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g.dep
package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g: package/package_ti.drivers.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.sm4g: package/package_ti.drivers.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g.dep
package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g: ./gpio/GPIOCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.sm4g: ./gpio/GPIOCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/I2C.om4g.dep
package/lib/lib/drivers_ccware_instrumented/I2C.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/I2C.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/I2C.om4g: I2C.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/I2C.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/I2C.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/I2C.sm4g: I2C.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/I2C.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g.dep
package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g: ./i2c/I2CCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.sm4g: ./i2c/I2CCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/PWM.om4g.dep
package/lib/lib/drivers_ccware_instrumented/PWM.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/PWM.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/PWM.om4g: PWM.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/PWM.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/PWM.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/PWM.sm4g: PWM.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/PWM.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g.dep
package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g: ./pwm/PWMTimerCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.sm4g: ./pwm/PWMTimerCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g.dep
package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g: SDSPI.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/SDSPI.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/SDSPI.sm4g: SDSPI.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/SDSPI.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g.dep
package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g: ./sdspi/SDSPICC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.sm4g: ./sdspi/SDSPICC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/SPI.om4g.dep
package/lib/lib/drivers_ccware_instrumented/SPI.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/SPI.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/SPI.om4g: SPI.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/SPI.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/SPI.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/SPI.sm4g: SPI.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/SPI.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g.dep
package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g: ./spi/SPICC3200DMA.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.sm4g: ./spi/SPICC3200DMA.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/UART.om4g.dep
package/lib/lib/drivers_ccware_instrumented/UART.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/UART.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/UART.om4g: UART.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/UART.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/UART.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/UART.sm4g: UART.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/UART.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g.dep
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g: ./uart/UARTCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.sm4g: ./uart/UARTCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g.dep
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g: ./uart/UARTCC3200DMA.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.sm4g: ./uart/UARTCC3200DMA.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g.dep
package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g: Watchdog.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/Watchdog.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/Watchdog.sm4g: Watchdog.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/Watchdog.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g.dep
package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g.dep: ;
endif

package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g: ./watchdog/WatchdogCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -I/db/vtree/library/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.sm4g: | .interfaces
package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.sm4g: ./watchdog/WatchdogCC3200.c lib/drivers_ccware_instrumented.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g -D gcc   -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_7_4  -O2   -I/home/xlibrary/trees/zumaprod/zumaprod-e09/tirtos_simplelink_2_11_01_09/products/CC3200_driverlib_1.0.2 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.sm4g: export LD_LIBRARY_PATH=

clean,m4g ::
	-$(RM) package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/I2C.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/PWM.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/SPI.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/UART.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/I2C.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/PWM.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/SDSPI.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/SPI.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/UART.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/Watchdog.sm4g
	-$(RM) package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.sm4g

lib/drivers_ccware_instrumented.am4g: package/lib/lib/drivers_ccware_instrumented/package/package_ti.drivers.om4g package/lib/lib/drivers_ccware_instrumented/./gpio/GPIOCC3200.om4g package/lib/lib/drivers_ccware_instrumented/I2C.om4g package/lib/lib/drivers_ccware_instrumented/./i2c/I2CCC3200.om4g package/lib/lib/drivers_ccware_instrumented/PWM.om4g package/lib/lib/drivers_ccware_instrumented/./pwm/PWMTimerCC3200.om4g package/lib/lib/drivers_ccware_instrumented/SDSPI.om4g package/lib/lib/drivers_ccware_instrumented/./sdspi/SDSPICC3200.om4g package/lib/lib/drivers_ccware_instrumented/SPI.om4g package/lib/lib/drivers_ccware_instrumented/./spi/SPICC3200DMA.om4g package/lib/lib/drivers_ccware_instrumented/UART.om4g package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200.om4g package/lib/lib/drivers_ccware_instrumented/./uart/UARTCC3200DMA.om4g package/lib/lib/drivers_ccware_instrumented/Watchdog.om4g package/lib/lib/drivers_ccware_instrumented/./watchdog/WatchdogCC3200.om4g lib/drivers_ccware_instrumented.am4g.mak

clean::
	-$(RM) lib/drivers_ccware_instrumented.am4g.mak
